#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-rstatix
Version  : 0.7.2
Release  : 2
URL      : https://cran.r-project.org/src/contrib/rstatix_0.7.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rstatix_0.7.2.tar.gz
Summary  : Pipe-Friendly Framework for Basic Statistical Tests
Group    : Development/Tools
License  : GPL-2.0
Requires: R-broom
Requires: R-car
Requires: R-corrplot
Requires: R-dplyr
Requires: R-generics
Requires: R-magrittr
Requires: R-purrr
Requires: R-rlang
Requires: R-tibble
Requires: R-tidyr
Requires: R-tidyselect
BuildRequires : R-broom
BuildRequires : R-car
BuildRequires : R-corrplot
BuildRequires : R-dplyr
BuildRequires : R-generics
BuildRequires : R-magrittr
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : R-tidyr
BuildRequires : R-tidyselect
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
for performing basic statistical tests, including t-test, Wilcoxon test, ANOVA, Kruskal-Wallis and correlation analyses. 
    The output of each test is automatically transformed into a tidy data frame to facilitate visualization. 
    Additional functions are available for reshaping, reordering, manipulating and visualizing correlation matrix.  
    Functions are also included to facilitate the analysis of factorial experiments, including purely 'within-Ss' designs 
    (repeated measures), purely 'between-Ss' designs, and mixed 'within-and-between-Ss' designs. 
    It's also possible to compute several effect size metrics, including "eta squared" for ANOVA, "Cohen's d" for t-test and 
    'Cramer V' for the association between categorical variables. 
    The package contains helper functions for identifying univariate and multivariate outliers, assessing normality and homogeneity of variances.

%prep
%setup -q -n rstatix

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713980085

%install
export SOURCE_DATE_EPOCH=1713980085
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rstatix/DESCRIPTION
/usr/lib64/R/library/rstatix/INDEX
/usr/lib64/R/library/rstatix/Meta/Rd.rds
/usr/lib64/R/library/rstatix/Meta/features.rds
/usr/lib64/R/library/rstatix/Meta/hsearch.rds
/usr/lib64/R/library/rstatix/Meta/links.rds
/usr/lib64/R/library/rstatix/Meta/nsInfo.rds
/usr/lib64/R/library/rstatix/Meta/package.rds
/usr/lib64/R/library/rstatix/NAMESPACE
/usr/lib64/R/library/rstatix/NEWS.md
/usr/lib64/R/library/rstatix/R/rstatix
/usr/lib64/R/library/rstatix/R/rstatix.rdb
/usr/lib64/R/library/rstatix/R/rstatix.rdx
/usr/lib64/R/library/rstatix/WORDLIST
/usr/lib64/R/library/rstatix/help/AnIndex
/usr/lib64/R/library/rstatix/help/aliases.rds
/usr/lib64/R/library/rstatix/help/paths.rds
/usr/lib64/R/library/rstatix/help/rstatix.rdb
/usr/lib64/R/library/rstatix/help/rstatix.rdx
/usr/lib64/R/library/rstatix/html/00Index.html
/usr/lib64/R/library/rstatix/html/R.css
/usr/lib64/R/library/rstatix/tests/spelling.R
/usr/lib64/R/library/rstatix/tests/testthat.R
/usr/lib64/R/library/rstatix/tests/testthat/test-add_x_position.R
/usr/lib64/R/library/rstatix/tests/testthat/test-anova_test.R
/usr/lib64/R/library/rstatix/tests/testthat/test-emmeans_test.R
/usr/lib64/R/library/rstatix/tests/testthat/test-get_n.R
/usr/lib64/R/library/rstatix/tests/testthat/test-get_summary_stats.R
/usr/lib64/R/library/rstatix/tests/testthat/test-levene_test.R
/usr/lib64/R/library/rstatix/tests/testthat/test-p_mark_significance.R
/usr/lib64/R/library/rstatix/tests/testthat/test-remove_ns.R
/usr/lib64/R/library/rstatix/tests/testthat/test-shapiro_test.R
/usr/lib64/R/library/rstatix/tests/testthat/test-wilcox_test.R
